# Generated by Django 5.0.2 on 2024-04-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_model', models.CharField(blank=True, choices=[('jpg', 'image JPEG'), ('png', 'Image PNG'), ('mp4', 'Vidéo MP4'), ('mp3', 'Audio MP3')], max_length=5, null=True)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/')),
                ('file_description', models.TextField()),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cms_users.appusers')),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_model', models.CharField(blank=True, choices=[('h1', 'Titre de niveau 1'), ('h2', 'Titre de niveau 2'), ('h3', 'Titre de niveau 3'), ('h4', 'Titre de niveau 4'), ('h5', 'Titre de niveau 5'), ('h6', 'Titre de niveau 6'), ('p1', 'Paragraphe de niveau 1'), ('p2', 'Paragraphe de niveau 2')], max_length=5, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cms_users.appusers')),
            ],
        ),
    ]
